---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-sender-canonical
  namespace: default
data:
  sender_canonical: |
    /^(.+)@source-domain-1.example.com$/  ${1}@dest-domain-1.example.com
